### ISSUE TITLE
Make a landing page

### ISSUE THREAD

**Issue by arnab2001** [arnab2001/socialite#43]
![image](https://github.com/arnab2001/socialite/assets/63441472/d904d279-7c47-479d-91cd-f52cf154b63f)

here's a sketch of how it might look like. Use you imagination for rest

**Comment by Sneha123-zudo** [comment]
Please assign me this issue I am interested in solving this issue.

**Comment by arnab2001** [comment]
@Sneha123-zudo assigned you the issue , best of luck 🤞

**Comment by Sneha123-zudo** [comment]
will you add a apertre label also.

**Comment by arnab2001** [comment]
Yes
